version: "3.9"
services:
  geoserver:
    image: docker.osgeo.org/geoserver:2.25.0
    container_name: geoserver
    ports:
      - 9090:8080
    volumes:
      - /data/docker_volumes/geoserver/geoserver_data:/opt/geoserver_data

