version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins
    restart: always
    ports:
      - "8088:8080"
      - "50000:50000"
    environment:
      privileged: true
      user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker_volumes/jenkins:/var/jenkins_home
networks:
  jenkins:
    name: jenkins
    driver: bridge
