version: "3.9"
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer 
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/docker_volumes/portainer/data:/data
